const test=require('node:test'),assert=require('node:assert/strict');
const {changePlan,validateSwap,paymentStatus}=require('../services/profile-actions');
function database({status='active',plan='Standard',failUser=false}={}){
 let state={sub:{status,package:plan,end_date:'2099-10-07T00:00:00Z'},subjects:['mathematics','english','history','geography']},snapshot;const calls=[];
 const client={release(){},async query(sql,args){calls.push({sql,args});if(sql==='BEGIN'){snapshot=structuredClone(state);return{rows:[]};}if(sql==='ROLLBACK'){state=snapshot;return{rows:[]};}if(sql==='COMMIT'||sql.includes('pg_advisory'))return{rows:[]};if(sql.startsWith('SELECT * FROM smartclass_subscriptions'))return{rows:[state.sub]};if(sql.startsWith('SELECT subjects'))return{rows:[{subjects:state.subjects}]};if(sql.includes("SET status = 'cancelled'")){state.sub.status='cancelled';return{rows:[]};}if(sql.includes("SET package = 'Basic'")){state.sub.package='Basic';state.sub.subjects=JSON.parse(args[1]);return{rows:[]};}if(sql.startsWith('UPDATE users')){if(failUser)throw Error('database failure');state.subjects=JSON.parse(args[1]);return{rows:[]};}throw Error(sql);}};
 return{pool:{connect:async()=>client},calls,get state(){return state;}};
}
test('cancel keeps actual paid end date and repeated cancellation is safe',async()=>{const db=database();const result=await changePlan(db.pool,'uuid','cancel');assert.equal(result.endDate,'2099-10-07T00:00:00.000Z');assert.equal(db.state.sub.status,'cancelled');await changePlan(db.pool,'uuid','cancel');assert.ok(!db.calls.some(c=>/SET.*end_date/.test(c.sql)));});
test('downgrade updates both subject lists while preserving expiry',async()=>{const db=database();await changePlan(db.pool,'uuid','downgrade');assert.equal(db.state.sub.package,'Basic');assert.deepEqual(db.state.subjects,['mathematics','english']);assert.deepEqual(db.state.sub.subjects,db.state.subjects);assert.equal(db.state.sub.end_date,'2099-10-07T00:00:00Z');});
test('failed subject save rolls the plan change back',async()=>{const db=database({failUser:true});await assert.rejects(changePlan(db.pool,'uuid','downgrade'),/database failure/);assert.equal(db.state.sub.package,'Standard');assert.equal(db.state.subjects.length,4);});
test('invalid downgrade does not change plan',async()=>{for(const options of [{plan:'Basic'},{status:'cancelled'}]){const db=database(options);await assert.rejects(changePlan(db.pool,'uuid','downgrade'));assert.equal(db.state.sub.package,options.plan||'Standard');}});
test('swap validates current paid subjects before checkout',async()=>{const pool={query:async()=>({rows:[{subjects:['mathematics','english'],status:'active',end_date:'2099-01-01'}]})};await validateSwap(pool,'uuid','mathematics','geography');for(const pair of [['mathematics','english'],['history','geography'],['mathematics','unsupported']])await assert.rejects(validateSwap(pool,'uuid',...pair));await assert.rejects(validateSwap({query:async()=>({rows:[]})},'uuid','mathematics','geography'));});
test('payment lookup is scoped to authenticated owner and exact checkout',async()=>{let params;const pool={query:async(sql,args)=>{assert.match(sql,/checkout_id = \$1 AND user_id = \$2/);params=args;return{rows:[{checkout_id:'ch_123',status:'pending',package:'swap_fee'}]};}};const result=await paymentStatus(pool,'owner','ch_123');assert.deepEqual(params,['ch_123','owner']);assert.equal(result.status,'pending');await assert.rejects(paymentStatus({query:async()=>({rows:[]})},'other','ch_123'),{status:404});});
