const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
function setup(error){const handlers={},calls=[];const secret=Buffer.from('test-webhook-secret-only').toString('base64');
 const router={post(route,...fns){handlers[route]=fns.at(-1);},get(route,...fns){handlers[route]=fns.at(-1);}};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../routes/yoco.js'),'utf8'),{require:name=>name==='express'?{Router:()=>router}:name==='crypto'?crypto:name.includes('yoco-settlement')?{settleYocoEvent:async(...args)=>{calls.push(args);if(error)throw error;return{received:true,subscription:true};}}:{},process:{env:{YOCO_SECRET_KEY_SMARTCLASS:'sk_live_testonly',YOCO_WEBHOOK_SECRET:'whsec_'+secret}},console:{log(){},error(){}},Buffer,Date,JSON,setTimeout,clearTimeout,AbortController,fetch:async()=>{throw Error('Must not fetch checkout by payment ID');},module:{exports:{}}});
 const body=Buffer.from(JSON.stringify({type:'payment.succeeded',payload:{id:'p_demo',metadata:{checkoutId:'ch_demo'}}}));const timestamp=String(Math.floor(Date.now()/1000)),id='msg_demo';const signature=crypto.createHmac('sha256',Buffer.from(secret,'base64')).update(id+'.'+timestamp+'.'+body.toString()).digest('base64');
 const req={body,headers:{'webhook-id':id,'webhook-timestamp':timestamp,'webhook-signature':'v1,'+signature}};
 const res={code:200,status(c){this.code=c;return this;},json(data){this.body=data;return this;}};return{handler:handlers['/webhook'],req,res,calls};
}
test('verified raw signed payload reaches settlement without an external checkout lookup',async()=>{const t=setup();await t.handler(t.req,t.res);assert.equal(t.res.code,200);assert.equal(t.calls.length,1);assert.equal(t.calls[0][1].payload.metadata.checkoutId,'ch_demo');});
test('forged and stale deliveries never reach settlement',async()=>{for(const bad of ['signature','stale']){const t=setup();if(bad==='signature')t.req.headers['webhook-signature']='v1,forged';else t.req.headers['webhook-timestamp']='1';await t.handler(t.req,t.res);assert.equal(t.res.code,401);assert.equal(t.calls.length,0);}});
test('database and missing-row failures return non-2xx so Yoco retries',async()=>{for(const error of [new Error('db failed'),Object.assign(new Error('row pending'),{status:503})]){const t=setup(error);await t.handler(t.req,t.res);assert.ok(t.res.code>=500);assert.equal(t.res.body.received,undefined);}});
